### ISSUE TITLE
SubmodelElementCollection valueOnly serialization

### ISSUE THREAD

**Issue by mansei** [eclipse-basyx/basyx-java-server-sdk#252]
Hi,

I'm reading submodel elements 'valueOnly' by api call: 
GET /submodels/{submodelIdentifier}/submodel-elements/{idShortPath}/$value
IF I understand the specification correctly for a SubmodelElementCollection I should get back an unnamed object with the elements as properties.
Currently I get back an array with objects like this:
[
  {
    "Number": "22.5"
  },
  {
    "String": "Something"
  }
]

I expected:
{
	"Number": 22.5,
	"String": "Something"
}

If I'm calling the same api on different hierarchy levels (e.g. reading hole submodel), the same situation.

Can you please help me, is it a misinterpretation on my side of this sentence from the specification ?
'SubmodelElementCollection is serialized as named JSON object with ${SubmodelElementCollection/idShort} as the name of the containing JSON property. The elements contained within the struct are serialized according to their respective type with ${SubmodelElement/idShort} as the name of the containing JSON property.'

BR
Manfred

Component: aas-environment
Version: milestone_02 
Api: GET /submodels/{submodelIdentifier}/submodel-elements/{idShortPath}/$value
RBAC: no

**Comment by FrankSchnicke** [comment]
The exact return value of _../$value_ is currently being discussed (cf. https://github.com/admin-shell-io/aas-specs-api/issues/185 and related issues) since it is underspecified. Thus, I expect an update on how to handle this soon and we will align with the updated specification. However, until the specification is updated, we will avoid changing this point to avoid having multiple changes.
