### ISSUE TITLE
Invoking /shells with invalid asset ids returns 500

### ISSUE THREAD

**Issue by otto-ifak** [eclipse-basyx/basyx-java-server-sdk#279]
I am using the docker setup from the `examples` folder. When I invoke

```
http://localhost:8081/shells?assetIds=INVALID
```

the server responds with error code 500.

**Comment by FrankSchnicke** [comment]
The reason for this is that the _assetIds_ parameter is not implemented in BaSyx. You can see all implemented endpoints here:
https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/basyx.aasrepository

**Comment by otto-ifak** [comment]
Thanks for the quick reply. According to https://github.com/admin-shell-io/aas-specs-api/blob/a6956e56975c867494ef1d9701444cd2082342a6/AssetAdministrationShellRepositoryServiceSpecification/V3.0_SSP-001.yaml#L51 isn't `GetAllAssetAdministrationShellsByAssetId` a required part of the Repo Interface?

Furthermore, the server responds:
```
{"type":"about:blank","title":"Internal Server Error","status":500,"detail":"Failed to convert \'assetIds\' with value: \'INVALID\'","instance":"/shells"}'
```
From the error message, it seems that it tries to parse the `assetIds`. It also should return something else than 500, as this is more related to serious problems on the server side.

**Comment by FrankSchnicke** [comment]
According to the profile, the superpaths (e.g., _/shells/{aasIdentifier}/submodels/{submodelIdentifier}/submodel-elements_) are also required. However, we decided not to implement them in BaSyx due to the drawbacks discussed in https://github.com/admin-shell-io/aas-specs-api/issues/113. 

In my opinion, the same issues may arise when using the _GetAllAssetAdministrationShellsByAssetId_ since in a fully distributed deployment it may not behave as expected due to the AAS being searched for are contained in another repository. In these contexts, using the AAS Discovery would be better. I will create a ticket in the aas api spec repo to highlight this issue.

> It also should return something else than 500, as this is more related to serious problems on the server side.
You're right, 404 or similar would be a better return value.
