### ISSUE TITLE
[BUG] Updating ValueOnly on a Submodel directly is not working

### ISSUE THREAD

**Issue by FelixMethe** [eclipse-basyx/basyx-java-server-sdk#408]
**Describe the bug**
Trying to update a submodels valueOnly directly, returns a `Failed to read request`.

**To Reproduce**

Let's say I have a Submodel:

```shell
curl --request POST \
  --url 'http://localhost:8081/submodels?=' \
  --header 'Content-Type: application/json' \
  --data '{
	"modelType": "Submodel",
	"kind": "Instance",
	"id": "mySubmodel",
	"submodelElements": [
		{
			"modelType": "Property",
			"value": "Hello, World!",
			"valueType": "xs:string",
			"idShort": "myProperty"
		}
	]
}'
```

GETing `$value` works as expected

```shell
curl --request GET \
  --url 'http://localhost:8081/submodels/bXlTdWJtb2RlbA/$value?=' \
  --header 'Content-Type: application/json'
```

And returns:

```JSON
{
	"myProperty": "Hello, World!"
}
```

But now when I try to Call PATCH

```shell
curl --request PATCH \
  --url 'http://localhost:8081/submodels/bXlTdWJtb2RlbA/$value?=' \
  --header 'Content-Type: application/json' \
  --data '{
	"myProperty": "Hello"
}'
```

I get the following error:

```JSON
{
	"type": "about:blank",
	"title": "Bad Request",
	"status": 400,
	"detail": "Failed to read request",
	"instance": "/submodels/bXlTdWJtb2RlbA/$value"
}
```

**BaSyx (please complete the following information):**

- BaSyx Version: 2.0.0-SNAPSHOT
- BaSyx SDK: Java V2
- AAS Version: DotAAS V3

**BaSyx configuration**
The default config:
[basyx-setup-11.zip](https://github.com/user-attachments/files/16797675/basyx-setup-11.zip)

**System (please complete the following information):**
Tested on a Mac [M1 (arm)] & VPS Linux Server

**Comment by aaronzi** [comment]
Hello @FelixMethe,
can you please provide the URL you are sending the request to?
Or better, maybe the entire request (for example in cURL format), so that we can reproduce this.

**Comment by FelixMethe** [comment]
Hello @aaronzi,

Thank you for your quick response. I have updated the issue.

**Comment by aaronzi** [comment]
Sorry for the late response. We were able to reproduce this and will work on a fix.

**Comment by FriedJannik** [comment]
Hi @FelixMethe,
the patch Endpoint for the Submodel Value only accepts a List of SubmodelElements ( not in value only representation )
This is due to a lack of specification in the AAS Spec on how the Submodel Value Only should look like and a general confusion about various ValueOnly Endpoints defined in the spec.
See:
https://github.com/admin-shell-io/aas-specs-api/issues/251
https://github.com/admin-shell-io/aas-specs-api/issues/100
and:
![image](https://github.com/user-attachments/assets/fa25e68d-7364-4f0d-8548-9da169eac264)

The request you would need to send looks something like this:
```
curl --request PATCH \
  --url 'http://localhost:8081/submodels/bXlTdWJtb2RlbA/$value?=' \
  --header 'Content-Type: application/json' \
  --data '[
		{
			"modelType": "Property",
			"value": "Hello, World!",
			"valueType": "xs:string",
			"idShort": "myProperty"
		}
	]'
```

**Comment by LinhPhan210** [comment]
Hi @FriedJannik, Hi @aaronzi 

Somehow the specs from the Swagger (https://app.swaggerhub.com/domains/Plattform_i40/Part2-API-Schemas/V3.0#/components/schemas/ValueOnly) and the specs from Github repository (https://github.com/admin-shell-io/aas-specs-api/blob/main/Part2-API-Schemas/openapi.yaml) are not similar.

![image](https://github.com/user-attachments/assets/18cc7131-478c-41fc-9b9d-2b1408042355)

![image](https://github.com/user-attachments/assets/d66c8c90-46ce-4ab2-93a7-34a937ca7b7c)

As i have worked with IDTA server version 3, i believe that the one in github repository is much correct. Otherwise, what returned by Basyx (SNAPSHOT 2.0.0) GET method also follow spec from Github repo.
