### ISSUE TITLE
[BUG] Deletion of an AAS from the AAS Registry via aas-gui:v2 is not working

### ISSUE THREAD

**Issue by oliverbusch** [eclipse-basyx/basyx-java-server-sdk#432]
Deletion of an AAS from the AAS Registry via aas-gui:v2 is not working

**To Reproduce**
1. Setup BaSyx (examples/BaSyxMinimal)
2. Open http://localhost:3000/
3. Click on 'X" behind first entry TestAssetAdministrationShell
4. Confirm Dialog "Are you sure you want to delete the AAS from the AAS Registry?"
5. See error

**Expected behavior**
Asset should be deleted

**BaSyx (please complete the following information):
- BaSyx Version [v2.0] - Main Branch 04.09.2024

**Screenshots**
![image](https://github.com/user-attachments/assets/a13b782c-bd90-4e29-b6df-61c42128b15a)
![image](https://github.com/user-attachments/assets/f90983a4-9da7-4e87-bb11-4d0a05b78fe7)

**System (please complete the following information):
OS: [Docker on Linux]

**Comment by aaronzi** [comment]
Hi @oliverbusch,

we recently updated this feature because we noticed the same bug. In the newest version of the AAS Web UI it looks like this:

![Image](https://github.com/user-attachments/assets/6f91b189-aec4-48c5-bcf3-5740bad64426)

The tag for the container image on dockerhub is `v2-240801`.
You can find it here: [eclipsebasyx/aas-gui:v2-240801](https://hub.docker.com/layers/eclipsebasyx/aas-gui/v2-240801/images/sha256-bafcd678ff42b47c4a730fa64da48dee85fda46f45c7d711d298d98b40e3bebb?context=explore)

**Comment by oliverbusch** [comment]
I've the problem with the mentioned container image
a1c5a9949e2a   eclipsebasyx/aas-gui:v2-240801                              "/usr/src/app/entryp…"   4 days ago     Up 4 days                   80/tcp, 0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                                      aas-web-ui_v2

For me it looks like that the bug is still there.

**Comment by oliverbusch** [comment]
With the version from today (09:09:2024 13.20) it works again.
