### ISSUE TITLE
Components and GUI

### ISSUE THREAD

**Issue by abhishekmaha23** [eclipse-basyx/basyx-java-server-sdk#46]
I'm currently looking into deploying multiple components and am identifying the following:

I'm able to deploy the AAS Repository 2.0.0-snapshot (eclipsebasyx/aas-repository:2.0.0-SNAPSHOT), and the submodel repository 2.0.0-snapshot (eclipsebasyx/submodel-repository:2.0.0-SNAPSHOT).
- In the AAS repository - the AASX upload method is a stub and I also can't seem to get the feature to load - perhaps I could offer a PR if it's in the queue for development?
- The Submodel repository does not seem to load the MQTT settings though I used the same properties file as for the AAS repository
- Got a 400 empty when trying to add a Submodel to the submodel repository, though I tested it in the previous Basyx version - maybe I have to update something for the new AAS spec, but I got an empty response which could be changed
- Is the AAS Web GUI (eclipsebasyx/aas-gui:v230703) currently incompatible with these components? 
It needs both a server and a registry - I couldn't get the repository to connect in place of the server.

**Comment by abhishekmaha23** [comment]
Regarding the third point, it's exactly the same as #36 
I have a large submodel JSON file, and it would help to have some error logs to be able to modify on the go

**Comment by FrankSchnicke** [comment]
> AASX Upload

This is not implemented right now. If you would like to contribute this feature, we will glaldy merge. Please note, however, that this should be implemented as a feature of the AAS Environment component, not as feature of any of the repositories since only the environment can ensure inclusion of all required repositories

> MQTT settings

There was an outdated documentation in regard to where to mount the application.properties. Can you double-check if this fixed your issue?

> Better Error Logs

True, this is something which we are planning for in the future. 

> AAS Web GUI

For now, the UI is only working with BaSyx V1. We will update it in future to the newest version. However, this will still take some time.

**Comment by FrankSchnicke** [comment]
Yes, they should be moved into basyx.aasenvironment as new project - e.g., _basyx.aasenvironment-feature-aasxupload_

**Comment by FrankSchnicke** [comment]
The AAS GUI is now available also for version 2, see the examples folder for a deployment. 

Are you still interested in raising a PR for AASX upload? If yes, I will reopen this issue.
