### ISSUE TITLE
[FEATURE] submodel repository - Adding modular support for semantic models 

### ISSUE THREAD

**Issue by mmaeffert** [eclipse-basyx/basyx-java-server-sdk#477]
*Problem:*

The component submodel repository lets you store a submodel. However, it only accepts very limited attributes: 
https://aas-core-works.github.io/aas-core-meta/v3/Submodel.html
If I know want to store a battery pass submodel for example with performance data[ according to standard](https://github.com/eclipse-tractusx/sldt-semantic-models/tree/main/io.catenax.battery.battery_pass/6.0.0/gen), the api removes any additional information, storing only the predefined attributes.

*I would like:*

Since the standards for semantic models are already defined with their constraints, I would like to add semantic models like [this ](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/6.0.0/gen/BatteryPass-schema.json) for validation and ultimately storing them in a database.

**Comment by aaronzi** [comment]
Hello @mmaeffert,

could you explain which data is actually lost from the performance data? Are you talking about the PerformanceEntity from the [example AASX-file](https://github.com/eclipse-tractusx/sldt-semantic-models/blob/main/io.catenax.battery.battery_pass/6.0.0/gen/BatteryPass.aasx)?

Regarding the last point from your issue:
Do you want to store this schema using the submodel repository with mongoDB as backend so that it's saved in a database?

**Comment by mmaeffert** [comment]
@aaronzi Error was on my end

**Comment by aaronzi** [comment]
Alright, nice to hear that you found the problem
