### ISSUE TITLE
[BUG] Inability to Upload an AASX File Created with Package Explorer

### ISSUE THREAD

**Issue by JS-Aibel** [eclipse-basyx/basyx-java-server-sdk#514]
**Describe the bug**
Inability to Upload an AASX File Created with Package Explorer version 2024-06-10.
It seems to be related to this answer, https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/500#issuecomment-2437001447
On second thought, based on your comment, I guess this issue will be fixed in the pull request https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/503 ?

**To Reproduce**
1.	Create a simple Asset Administration Shell (AAS) using the Package Explorer.
2.	Attempt to upload the AASX file using the aas-ui.
3.	Encounter an error with status code 400.

**Observations**
- The AAS is present in the repository.
- The AAS is absent in the registry.
- The submodel is missing in both the submodel repository and the submodel registry.

These observations seem similar to the issue https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/500

**Additional Information**
- The AASX file can be read using the basyx-python-sdk.
- An AASX file created with the basyx-python-sdk can be successfully uploaded.

**Expected behavior**
Uploaded with no errors.

**BaSyx (please complete the following information):**
BaSyx Version [ v2.0]
BaSyx SDK [Python]
AAS Version [DotAAS V3]

**BaSyx configuration**
Default from the Quick Start Guide.

**Comment by aaronzi** [comment]
Hi @JS-Aibel,

Can you share your AAS that you created in AASPE? That way we can have a look at what might be wrong (on our end or in the AAS that you created in the AASPE).

**Comment by JS-Aibel** [comment]
Thank you for the reply, @aaronzi 
It is any AASX I create with Package Explorer version 2024-06-10. I will e-mail you an example.

**Comment by aaronzi** [comment]
Thank you, I will have a look.

**Comment by aaronzi** [comment]
Found the problem. It seems that the asset type causes the problem and as discussed in #500 the registry integration creates the entry in the repo even if the entry in the registry could not be created. Oddly enough, this should have been fixed in the current version of BaSyx 2.0.0_SNAPSHOT.

This only happens if the asset type is set to `NotApplicable`. Attached are two shells to reproduce this. One uses the `Instance` type which works and one uses `NotApplicable`.

[test-instance-asset-kind.zip](https://github.com/user-attachments/files/17630403/test-instance-asset-kind.zip)
[test-not-applicable-asset-kind.zip](https://github.com/user-attachments/files/17630404/test-not-applicable-asset-kind.zip)
To try the demo shells, change the file extension to .aasx.

We will have a look into this and come up with a fix.

**Comment by aaronzi** [comment]
The newest images did not include the pull request that fixes #500.
I pushed a new version of the AAS Environment to Dockerhub. I will now also update the 2.0.0_SNAPSHOT tag for all other components as well. This fixes the problem.
