### ISSUE TITLE
“Error! Server responded with: Error: Error status: 409” by usage of IDTA 02006-2-0_Template_Digital Nameplate

### ISSUE THREAD

**Issue by MartinRudolph96** [eclipse-basyx/basyx-java-server-sdk#537]
Hello,

when we, the energy informatics group of the Fraunhofer IOSB-AST, built an AASX file together with a project partner, based on the IDTA 02006-2-0_Template_Digital Nameplate given via [http://smt-repo.admin-shell-io.com/](http://smt-repo.admin-shell-io.com/), we get the error “Error! Server responded with: Error: Error status: 409”, even though there is guaranteed no network issue, as it works with different files at any given time. We reviewed the generated files multiple times via different programs like the Package Explorer. The errors seems to based on some serialization error, even though all the needed concept descriptions are given. 

This stops us from using BaSyx as our AAS framework for the continuous development of an energy market data space. We could also review the files individually.

**Comment by aaronzi** [comment]
Hello @MartinRudolph96,

I have tried to reproduce the problem you describe. I assume that the error you see is caused by an inconsistent state of the BaSyx infrastructure caused by a problem that occurred earlier.

The error 409 means that there is a conflict, probably caused by trying to insert a data element (AAS) that already exists in the repository.

The actual error happens before when trying to insert an AAS including creating it's descriptor for the AAS registry when a templateId is set. The actual bug is described in issue #525.

When you try to insert the AAS for the first time, you will get an error 500 because of the actual bug. In this case, the AAS is probably added to the repository, but not to the registry. That's why you can't see it in the BaSyx UI. If you try to add the same AAS again you will get error 409 because the AAS already exists in the AAS repository.

Assuming that this is the case, please update to the newest Docker images (delete the old snapshot images and do a fresh download). The newest images include a fix that prevents this inconsistent state of the infrastructure.

Nevertheless, we will inform you once the actual bug described in issue #525 has been solved.

**Comment by MartinRudolph96** [comment]
It seems that the new image mostly resolved the issues in fact, thanks!

Also, please keep me updated on the related issue. :)
